version: '3.8'
services:
  laravel-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
volumes:
  postgres_data:
